### ISSUE TITLE
Change Event

### ISSUE THREAD

**Issue by agrulich** [mm-jsr/jsr#12]
I apologize in advance for being a complete novice, but I love this slider and was wondering if there is a change event I use for when values are updated. The natural onchange event of the input control doesn't seem to fire.

**Comment by soanvig** [comment]
I laughed myself loud, that you found this script somewhere.

It's still not finished (it's only 0.0.2 beta in fact), and I propably won't finished it. Rewrite maybe. 

The slider doesn't include events inside itself. They were planned to be created just before final release.

I strongly advise You to switch to another script, but if You really want to use mm-jsr, then you can call the event here:
https://github.com/mm-jsr/jsr/blob/master/mm-jsr.js#L730
You just need to dispatch event You want somehow.
