### ISSUE TITLE
fault of the sum of values

### ISSUE THREAD

**Issue by plumthedev** [mm-jsr/jsr#41]
the most of mathematical activities is good as possible but right now i got this 
https://ibb.co/k5FwcNp
it does not look the best, adding numbers in js has its drawbacks

**Comment by soanvig** [comment]
Gonna look at it soon.

If you want You may also create PR with fix.

**Comment by soanvig** [comment]
BTW please provide me with your JSR configuration :)

**Comment by plumthedev** [comment]
I will try to take care of it

`var rangeSlider = new JSR(['#jsr-1-1', '#jsr-1-2'], {
    min: 0,
    max: 350000,
    step: 5000,
    sliders: 2,
    values: [0, 350000],
    labels: {
        formatter: (value) => {
            let newVal = null;
            if(value > 1000){
                newVal = value / 1000 + ' 000 pkt';

                return newVal;
            }

            return value + ' pkt';
        } 
    },
    modules: {
        grid: false
    }
});`


grid turned out to be unnecessary so i disabled it

**Comment by plumthedev** [comment]
this is my config, i disabled grid because turned out to be unnecessary
```
var rangeSlider = new JSR(['#jsr-1-1', '#jsr-1-2'], {
    min: 0,
    max: 350000,
    step: 5000,
    sliders: 2,
    values: [0, 350000],
    labels: {
        formatter: (value) => {
            let newVal = null;
            if(value > 1000){
                newVal = value / 1000 + ' 000 pkt';

                return newVal;
            }

            return value + ' pkt';
        } 
    },
    modules: {
        grid: false
    }
});
```

I can take care of this fix and create pr
